package lnwallet

import (
	"github.com/roasbeef/btcd/blockchain"
	"github.com/roasbeef/btcutil"
)

// The CheckTransactionSanity function should be more widely used whenever
// we create transactions to sweep outputs generated by transactions.
// Even further, we should extend the function itself to return more details w.r.t
// why the transaction is invalid. If we can return info concerning which output(s)
// to remove to maintain a certain fee rate, then we can slowly prune inputs/outputs
// until we're able to sweep a transaction. This can be done in an iterative loop.
func CheckTransactionSanity(tx *btcutil.Tx) error {
	return blockchain.CheckTransactionSanity(tx)
}